version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=be_assignment
      - POSTGRES_USER=suji
      - POSTGRES_PASSWORD=suji_pass
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: